/* =========================================================
   Interview Assistant Mode (Interactive) — Minimal TS Skeleton
   - Controlled agent: outputs Actions only
   - UI is state-driven: UI = f(state)
   - Registry (tools) exists, but only some tools are rendered
   ========================================================= */

export type LanguageId = "en" | "zh" | "jp";
export type ViewType = "answer" | "compare" | "followups" | null;

export type SectionId =
    | "overview"
    | "state"
    | "dataflow"
    | "tradeoffs"
    | "highlights"
    | "links";

export type FilterId =
    | "state-management"
    | "derived-state"
    | "typescript"
    | "architecture"
    | "ui"
    | "api";

/** ---- Structured outputs (read-only, generated by headless tools) ---- */
export type AnswerPayload = {
    projectId: string;
    mode: "60sec" | "bullets" | "tradeoffs";
    what: string;
    why: string;
    tradeoffs: string[];
    highlights?: string[];
};

export type CompareRow = {
    dimension: "Problem" | "State Design" | "Data Flow" | "Trade-offs";
    left: string;
    right: string;
};

export type ComparePayload = {
    leftProjectId: string;
    rightProjectId: string;
    rows: CompareRow[];
};

export type FollowUpsPayload = {
    projectId: string;
    questions: string[];
};

export type ViewPayload =
    | { type: "answer"; data: AnswerPayload }
    | { type: "compare"; data: ComparePayload }
    | { type: "followups"; data: FollowUpsPayload };

/** ---- State for the assistant UI ---- */
export type AssistantState = {
    // navigation / selection
    activeProjectId: string | null;
    activeLanguageId: LanguageId;

    // controlled UI tuning
    filters: FilterId[];
    focusedSectionId: SectionId | null;

    // rendered view
    view: ViewType;
    payload: ViewPayload | null;

    // transparency
    lastUserIntent: string | null;
    actionLog: AssistantAction[]; // keep for debugging/replay
};

export const initialAssistantState: AssistantState = {
    activeProjectId: null,
    activeLanguageId: "en",
    filters: [],
    focusedSectionId: null,
    view: null,
    payload: null,
    lastUserIntent: null,
    actionLog: [],
};

/** ---- Guarded Actions (this is the ONLY thing the AI is allowed to emit) ---- */
export type AssistantAction =
    | {
    type: "SET_INTENT";
    intent: string;
}
    | {
    type: "SET_ACTIVE_PROJECT";
    projectId: string;
}
    | {
    type: "SET_LANGUAGE";
    languageId: LanguageId;
}
    | {
    type: "APPLY_FILTERS";
    filters: FilterId[];
    mode: "replace" | "merge";
}
    | {
    type: "FOCUS_SECTION";
    sectionId: SectionId | null;
}
    | {
    type: "RENDER_VIEW";
    view: Exclude<ViewType, null>;
    payload: ViewPayload;
}
    | {
    type: "CLEAR_VIEW";
}
    | {
    type: "NOOP";
    reason: string;
};


// Registry typed
type HeadlessToolName = "AnswerGenerator" | "CompareGenerator" | "FollowUpsGenerator";

type RenderedToolName = "AnswerCard" | "ComparisonTable" | "FollowUpQuestions" | "ActionLogPanel";

export type ToolRegistry = {
    headless: Record<
        HeadlessToolName,
        {
            description: string;
            run: (args: any) => ViewPayload; // keep minimal; can strongly-type per tool later
        }
    >;
    rendered: Record<
        RenderedToolName,
        {
            description: string;
            Component: React.ComponentType<any>;
        }
    >;
};


/** ---- Reducer: deterministic & testable ---- */
export function assistantReducer(
    state: AssistantState,
    action: AssistantAction
): AssistantState {
    switch (action.type) {
        case "SET_INTENT": {
            return {
                ...state,
                lastUserIntent: action.intent,
            };
        }

        case "SET_ACTIVE_PROJECT": {
            return {
                ...state,
                activeProjectId: action.projectId,
            };
        }

        case "SET_LANGUAGE": {
            return {
                ...state,
                activeLanguageId: action.languageId,
            };
        }

        case "APPLY_FILTERS": {
            const next =
                action.mode === "replace"
                    ? action.filters
                    : Array.from(new Set([...state.filters, ...action.filters]));

            return {
                ...state,
                filters: next,
            };
        }

        case "FOCUS_SECTION": {
            return {
                ...state,
                focusedSectionId: action.sectionId,
            };
        }

        case "RENDER_VIEW": {
            return {
                ...state,
                view: action.view,
                payload: action.payload,
            };
        }

        case "CLEAR_VIEW": {
            return {
                ...state,
                view: null,
                payload: null,
            };
        }

        case "NOOP": {
            return {
                ...state,
                actionLog: [...state.actionLog, action],
            }
        }

        default: {
            // Exhaustiveness check
            const _exhaustive: never = action;
            return state;
        }
    }
}

/** ---- Apply a batch plan (AI returns an array of actions) ---- */
export function applyActionPlan(
    state: AssistantState,
    actions: AssistantAction[]
): AssistantState {
    return actions.reduce((s, a) => {
        // append to log before applying, for transparency
        const withLog: AssistantState = {
            ...s,
            actionLog: [...s.actionLog, a],
        };
        return assistantReducer(withLog, a);
    }, state);
}

/** ---- Example: a "plan" that an agent could emit (for tests / demo) ---- */
export const examplePlan: AssistantAction[] = [
    { type: "SET_INTENT", intent: "Show best project for state management" },
    { type: "SET_ACTIVE_PROJECT", projectId: "portfolio" },
    { type: "APPLY_FILTERS", filters: ["state-management", "derived-state"], mode: "replace" },
    { type: "FOCUS_SECTION", sectionId: "state" },
    {
        type: "RENDER_VIEW",
        view: "answer",
        payload: {
            type: "answer",
            data: {
                projectId: "portfolio",
                mode: "60sec",
                what: "A React + TypeScript portfolio with i18n and project modal architecture.",
                why: "Demonstrates state-driven UI with single source of truth and derived state.",
                tradeoffs: [
                    "Active ID + derived entity keeps UI predictable but requires clear mapping logic.",
                    "Schema-guarded outputs reduce flexibility but improve reliability and testability.",
                ],
                highlights: ["activeProjectId as source of truth", "derived selectedProject", "clear data flow"],
            },
        },
    },
];
